[package]
name = "grr-plugin"
version = "0.1.0"
edition = "2021"
authors = "Archis Gore <me@archisgore.com>"
description = "A Rust template/sample for writing go-plugin compatible plugins."
readme = "README.md"
license = "Apache 2.0"
keywords = ["go-plugin", "golang", "gRPC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.6.2"